### ISSUE TITLE
Changement du propriétaire de l'app

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/nexusoss_ynh#3]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by selamanse** [comment]
@frju365 thank you for the warm welcome :) Will do so shortly!

**Comment by frju365** [comment]
excuse... je ne voulais pas le présenter comme ça. :smile:  Je suis du groupe Apps et la gestion des apps hors organisation est très difficile. De plus, cela ne change rien pour toi : tu auras toujours les droits écriture ou admin sur le repos. Tu pourras aussi ouvrir une équipe si tu veux travailler avec d'autres packageurs. Ceci est la base du travail en communauté. ;-)

**Comment by selamanse** [comment]
Ne t'inquiète pas, je comprends :) 
En ce moment, j'utilise Travis-ci comme vérification automatique (python lint tool) apres commit.
Existe-t-il une façon de tester automatiquement? Jenkins etc.?

**Comment by selamanse** [comment]
et voila ✅

**Comment by frju365** [comment]
oui, en effet, il existe jenkins. Yunohost possède deux instances : la première est officielle et teste toute les app qui sont en tant que working dans le manifest (https://ci-apps.yunohost.org/jenkins/), la deuxième est l'instance qui appartient au groupe app (je peux y ajouter ton application si tu le demande). Les test pour l'instance officielle sont prévu officiellement toutes les semaines, mais peuvent aussi être déclencher manuellement par une personne du groupe app ou alors un webhook type github. Pour l'instance du groupe app, tu peut demander à mettre un webhook aussi ou alors lancer des tests manuellement. 
Ce sont les instance web que j'ai présentées ici.

Une autre façon est d'utiliser chez toi package_check (https://github.com/YunoHost/package_check), une machine virtuelle en utilisant les images disque de build.yunohost.org.

Les instances web type jenkins utilisent package_check. Ce test permet de donner un niveau à ton app. Regarde : https://yunohost.org/#/packaging_apps_levels_fr

J'espère que ça t'a aidé et n'hésite pas à poser des questions. Pour cela tu peux utiliser les chaînes XMPP et le forum.

frju365
